### ISSUE TITLE
Compiling the binary for musl arm64 platforms

### ISSUE THREAD

**Issue by 101313** [jonascarpay/frecently#2]
Hey, great tool! Really glad I found it although a bit unfortunate as I can't get it to compile in my platform sadly.

I'm using alpine linux running on an arm64 platform and haskell isn't available in the repos and trying the installer lands me this: "Sorry, currently only 64-bit (x86_64) Alpine Linux binary is available." 

So I've been wondering if there is any chance you could compile it and perhaps offer the binary as release if you'd like, if that's possible altogether of course.

**Comment by jonascarpay** [comment]
Hey, thanks, I'm glad you like it. I think Nix should be able to build a static aarch64 binary, would that work for you? If so, I'll take a stab over the weekend.

**Comment by jonascarpay** [comment]
The releases.zip at the bottom of https://github.com/jonascarpay/frecently/actions/runs/2285521968 contains a static aarch64 binary, please check if that works, if you have a chance.

**Comment by 101313** [comment]
Ohhh hey, thanks a lot for taking care of it!

Its quite pleasing getting to find out about such gems so early not gonna lie :)
 I'll try it later today and let you know if anything goes wrong.

Thanks!

**Comment by jonascarpay** [comment]
>  I'll try it later today and let you know if anything goes wrong.

Make sure to use the latest action's artifacts: https://github.com/jonascarpay/frecently/suites/6708778095/artifacts/255409750

> Ohhh hey, thanks a lot for taking care of it!

Np, I hope it works for you

> Its quite pleasing getting to find out about such gems so early not gonna lie :)

Tell your friends!

**Comment by 1412031** [comment]
Hey, I'm the author of the issue, pardon my absence, life likes to throw some adventure for people here and there but thank god things are close to normal now so I can take my time tweaking my system here and there and your project was one of the highest in my list :))

Small talks aside, I'm replying to let you know that it worked perfectly on my platform which is even running on non-standard 16k pagesize by the way, so yes, it works for me, thanks :)

**Comment by jonascarpay** [comment]
Awesome!
